### ISSUE TITLE
Empty page Opcache panel

### ISSUE THREAD

**Issue by megabait1212** [SchumacherFM/Magento-OpCache#10]
Hello, I just installed extension and on page System/Opcache panel there is nothing, just empty, no any errors. In console is silent, log empty.

**Comment by SchumacherFM** [comment]
Please install OPCache

**Comment by megabait1212** [comment]
It's installed

**Comment by megabait1212** [comment]
I found problem, it's was because I didn't enable "Allow Symlinks"

**Comment by SchumacherFM** [comment]
Cool!
