### ISSUE TITLE
Not valid template file

### ISSUE THREAD

**Issue by mlabate** [SchumacherFM/Magento-OpCache#15]
Hi, trying to access to OpCache control panel on Magento backend, only a blank page is visible. Magento "system.log" says:
CRIT (2): Not valid template file:adminhtml/default/default/template/opcachepanel/panel.phtml

**Comment by npearson72** [comment]
Did you just install it.. or was it working before?

Trying clearing cache and session. Logout then log back in.

**Comment by mlabate** [comment]
I've just installed it.
I've already cleaned cache and session and performed a re-login, without success.

**Comment by mlabate** [comment]
Allowing symlinks under "system>configuration>developer" it seems to work.
Anyway, I can't allow symlinks on my production environment, so there's a way to make the module works avoiding use of modman?
Thx

**Comment by SchumacherFM** [comment]
Just copy it ;-)

**Comment by mlabate** [comment]
Just copying it, doesn't work.
I tried to copy both the entire content of *.zip package and only the "app" and "skin" directories.
But there's neither "OpCache Panel" link under backend "System" nor "OpCachePanel Settings" under backend "System>Configuration>System"

**Comment by mlabate** [comment]
Ok, it was a permission problem.
Thank you very much.
