### ISSUE TITLE
OpCache Panel not loaded

### ISSUE THREAD

**Issue by adeelmughal4u** [SchumacherFM/Magento-OpCache#16]
After installing it, I'm getting error

OpCache Module is not loaded! :-(

![screen shot 2016-06-24 at 16 18 53](https://cloud.githubusercontent.com/assets/1432237/16336477/61ecc598-3a27-11e6-8852-12d7a4e1417e.png)

**Comment by dannydnz** [comment]
Are you sure your've enabled the opcache module for php?
Check  your phpinfo(). Look for opcache.

**Comment by adeelmughal4u** [comment]
Ohh yes, now its working fine... Thanx for helping. :)

**Comment by leek** [comment]
Closing issue since @adeelmughal4u got it working.
