### ISSUE TITLE
How to clear cache via command line? Curl?

### ISSUE THREAD

**Issue by brandontamm** [SchumacherFM/Magento-OpCache#17]
Can you give an example of how to clear cache with Curl?

Thank you!

**Comment by SchumacherFM** [comment]
here is the code:

https://github.com/SchumacherFM/Magento-OpCache/blob/master/src/app/code/community/SchumacherFM/OpCachePanel/controllers/IndexController.php#L12

curl would be via a POST request:

```
$ curl -d "YourAPIKeyName:YourAPIKey" http://mystore.mage/opcachepanel/index/index
```

**Comment by brandontamm** [comment]
I set the ApiKeyName and API Key and ran the following code:

$ curl -d "ClearOpcacheRandomStringGenerat:1q2w3e4r5t6y7u8i9o0pazsxdcfvgbhn" http://staging.quickattach.com/opcachepanel/index/index

Status: 404 File not found

Any ideas?

**Comment by SchumacherFM** [comment]
Maybe your POST parameter is incorrectly formed.
